#!/bin/bash
#PBS -l nodes=1:ppn=20
#PBS -l walltime=01:00:00
#PBS -N myjob1
#PBS -o myjob1.out
#PBS -e myjob1.err
#PBS -q workq
#PBS -A loni_cyen405
#PBS -m e
#PBS -M ama067@latech.edu
work="/home/m3jpuv/lab_2"
CFILE="lab2_1a"
cd $work
./$CFILE
